CREATE DATABASE IF NOT EXISTS adgeo;
USE adgeo;

DROP TABLE IF EXISTS locations;

CREATE TABLE IF NOT EXISTS locations(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(1000),
coordinates VARCHAR(5000) 
);